# Generated by Django 6.0.4 on 2026-04-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_is_active_to_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printermodel',
            options={'ordering': ['manufacturer', 'name'], 'verbose_name': 'Printer Model', 'verbose_name_plural': 'Printer Models'},
        ),
        migrations.AddField(
            model_name='printermodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
