# Generated by Django 6.0.4 on 2026-04-27 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_add_is_active_to_printer_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='printer_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printers', to='inventory.printermodel'),
        ),
    ]
