# Generated by Django 6.0.4 on 2026-04-29 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_printer_printer_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='printer_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printers', to='inventory.printermodel'),
        ),
        migrations.AlterField(
            model_name='supplytype',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name='custodian',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_custodian'),
        ),
        migrations.AddConstraint(
            model_name='printer',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_printer'),
        ),
        migrations.AddConstraint(
            model_name='printermodel',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'name'), name='unique_printer_model'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_supplier'),
        ),
    ]
