# Generated by Django 6.0.4 on 2026-04-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_printer_image_supply_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='name_slug',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
