# Generated by Django 6.0.4 on 2026-04-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_add_name_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='name_slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
